### ISSUE TITLE
 Create get and set for all fields in Rede Entity 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [thiagogomesverissimo/uspdev#2]
@leandroramos

**Comment by leandroramos** [comment]
`public function getNome()
    {
        return $this->nome;
    }

    public function setNome($nome)
    {
        $this->nome = $nome;
    }

    public function getIprede()
    {
        return $this->iprede;
    }

    public function setIprede($iprede)
    {
        $this->iprede = $iprede;
    }

    public function getCidr()
    {
        return $this->cidr;
    }

    public function setCidr($cidr)
    {
        $this->cidr = $cidr;
    }`
